# fly.toml app configuration file generated for fastapi-car on 2023-07-22T01:50:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fastapi-car"
primary_region = "hkg"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
